### ISSUE TITLE
0110215046_#1

### ISSUE THREAD

**Issue by isfaaghyth** [yukhijrah/QA#1]

**Comment by hlmy27** [comment]
Nama Lengkap: Muhammad Fadhil Hilmi
NIM: 0110216037
Judul Tugas 1 : Kumpulan Hadist
Link Repo: https://github.com/yukhijrah/Pemrograman-Mobile/tree/master/KumpulanHadits
Judul Tugas 2 : Slicing Mockup to XML Code
Link Repo : https://github.com/yukhijrah/Pemrograman-Mobile/tree/master/Runtastic

Assalamu'alaikum bang, untuk tugas pengerjaan dua tugas diatas. sebelumnya memang dikerjakan secara berkelompok sesuai dengan kesepatakan pada awal - awal pertemuan. jadi pada awal praktikum saya mengerjakannya berbarengan dengan satria di laptopnya satria. lalu untuk pelaporan nama pengumpulan tugasnya ada link repo : https://github.com/yukhijrah/Pemrograman-Mobile. terima kasih sebelumnya bang :+1: 

Wassalamu'alaikum wr wb

**Comment by isfaaghyth** [comment]
waalaikumsalam, udah @hlmy27, silahkan di cek kmbli.
