### ISSUE TITLE
0110216031_#2

### ISSUE THREAD

**Issue by satriasuryan** [yukhijrah/QA#2]
Nama Lengkap: Satria Suryanegara
NIM: 0110216031
Judul Tugas: Slicing Mockup to XML Code
Link Repo: https://github.com/yukhijrah/Pemrograman-Mobile/tree/master/Runtastic

Assalamualaikum, bang jadi ini yang slicing mockup sbenernya udah push dari lama, cuma kayanya ane salah cara pushnya pake github desktop, jadinya pas push yang recycler view, branch yang slicing xml ini kebawa ke branch recycler view, mohon sekiranya yang slicing bisa diberi nilai dan dinilai juga tepat waktu hehehe terimakasih

**Comment by isfaaghyth** [comment]
Waalaikumsalam, done satria.
