### ISSUE TITLE
0110216056_#6

### ISSUE THREAD

**Issue by faizkhoiron** [yukhijrah/QA#3]
Nama Lengkap: Faiz Khoiron
NIM: 0110216056
Judul Tugas: Network Request Using Retrofit
Link Repo: https://github.com/yukhijrah/portalti16

Assalamu'laikum Warahmatullahi Wabarakatuh, ini saya udah update retrofit yg terbaru, sebenernya udah kerjain dari 2 hari yg lalu cuma lupa di push aja bang.

**Comment by isfaaghyth** [comment]
waalaikumsalam, done is.
