### ISSUE TITLE
0110216010_#2

### ISSUE THREAD

**Issue by anifatulaufah** [yukhijrah/QA#4]
Nama Lengkap: Anifatul Aufah
NIM: 0110216010
Judul Tugas: Slicing Mockup to XML Code
Link Repo: https://github.com/yukhijrah/LayoutInbox.git

Assalamu'alaikum ka, untuk tugas ini kenapa nilai masih 0. padahal sudah push tugasnya.terimakasih

**Comment by isfaaghyth** [comment]
waalaikumsalam, maaf fa, kelewat. udah ku apdet ya, silahkan cek lagi.
