### ISSUE TITLE
0110216019_#2

### ISSUE THREAD

**Issue by annisatahira** [yukhijrah/QA#5]
Nama Lengkap: Annisa Tahira
NIM: 0110216019
Judul Tugas: Slicing Mockup to XML Code Link Repo: https://github.com/yukhijrah/LayoutInbox.git

Assalamualaikum, kak untuk tugas yang slicing mockup sudah di push tugasnya, tapi kenapa nilainya masih 0?🙏

Terimakasih Ka

**Comment by isfaaghyth** [comment]
waalaikumsalam, maaf annisa tahira, saya kelewat, done ya.
