### ISSUE TITLE
0110216060_#1_#5

### ISSUE THREAD

**Issue by qifuataufiqs** [yukhijrah/QA#6]
Nama Lengkap : Sukmo Afri Ardi Saputro
NIM : 0110216060
Judul Tugas : Recyclerview with Adapter
Link Repo : https://github.com/yukhijrah/AppsDoa

**Comment by qifuataufiqs** [comment]
Nama Lengkap : Sukmo Afri Ardi Saputro
NIM : 0110216060
Judul Tugas : Network Request Using Retrofit
Link Repo : https://github.com/yukhijrah/qifuataufiqs-portalTI16

**Comment by isfaaghyth** [comment]
waalaikumsalam, done qifuat.
