### ISSUE TITLE
0110216031_#5

### ISSUE THREAD

**Issue by satriasuryan** [yukhijrah/QA#7]
Nama Lengkap: Satria Suryanegara
NIM: 0110216031
Judul Tugas: Network Request Using Retrofit
Link Repo: https://github.com/yukhijrah/retrofit-SatriaSuryanegara-0110216031

Assalamualaikum, bang jadi tugas yang ini ane udah ngumpulin tadi pagi, makasih bang

**Comment by isfaaghyth** [comment]
waalaikumsalam, done sat.
