### ISSUE TITLE
0110216056_#4

### ISSUE THREAD

**Issue by faizkhoiron** [yukhijrah/QA#8]
Nama Lengkap: Faiz Khoiron
NIM: 0110216056
Judul Tugas: Doa App with Fragment
Link Repo: https://github.com/yukhijrah/doafragment

Assalamu‘alaikum wa rahmatullahi wa barakatuh, bang. Ini tugas saya yg aplikasi doa dengan fragment, baru banget dikumpulin, mohon diperiksa ya bang, syukron.

**Comment by isfaaghyth** [comment]
waalaikumsalam, done is.
